spothero/SpotHeroSDK-iOS

- Sources/SpotHeroAPI/Search/Models/InOutPrivileges.swift
- Sources/SpotHeroAPI/Search/Models/MonthlyRate+StartDateOptions.swift
- Sources/SpotHeroAPI/Search/Models/MonthlyRate.swift
- Sources/SpotHeroAPI/Search/Models/MonthlyRedemptionInstructions.swift
Additional changes per the updates to the monthly spec.
> Some changes with monthly feedback

- Sources/SpotHeroAPI/Search/Airport/Models/AirportRate.swift
> Reordered AirportRate enums

- Package.resolved
- Package.swift
- Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift
- SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
This includes bumping UtilityBelt to 0.5.6 to include `ParameterConvertible` as well.
> Updated NetworkClient documentation

- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
Very small, just trying to use the URLs we'd use in the future.
> Updated to use production docs

- Sources/SpotHeroAPI/Core/Helpers/SpotHeroAPIClient.swift
- Sources/SpotHeroAPI/Search/SearchEndpoint.swift
**Issue Link**
IOS-2253
Exactly what the title states. We had this in a previous POC, so we seem to be aligned here, but I'm open to any and all suggestions to improve this going forward. I'm also okay with retroactively correcting a lot of this if we decide to adjust down the road.
> IOS-2253: Added SearchEndpoint

- .github/workflows/ci.yml
- Updated to iOS 12.1.
- Updated for iOS 14.1 and tvOS 14.1.
> Updated CI workflow for Xcode 12.1

- Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift
- Sources/SpotHeroAPI/Search/Transient/Models/TransientRate.swift
Title. Was in the wrong place.
> Moved EarlyBird to Rate object

- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
See title. This updated is based on [this documentation](https://spothero.atlassian.net/wiki/spaces/SEAR/pages/1636794577/Search+Transient+V2+Commuter+Card+Benefits+API+Contract+-+Short+Term).
> Added work lat/long to TransientFacility request params

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- Mintfile
- Package.resolved
- Package.swift
- Zincfile
**Issue Link**
IOS-2673
- Updated CI workflow to use Xcode 12.2.
- Bumped Gem, Mint, and SPM dependencies where applicable.
> IOS-2673: Bumped dependencies and updated CI workflow

- Package.swift
Just wanted to make sure this was listed properly.
> Updated UtilityBelt dependency in Package.swift

- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift
- Added `oversize` to both Airport search requests. (see [SEAR-1252](https://spothero.atlassian.net/browse/SEAR-1252) for more information)
> Added oversize parameter to Airport search requests

- Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate.swift
Added the `separate_application_type` field as part of [SEAR-1241](https://spothero.atlassian.net/browse/SEAR-1241).
> Added separate_application_type to MonthlyRate

- Sources/SpotHeroAPI/Search/Common/Models/FacilityOptions.swift
- Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyFacilityResult.swift
This accounts for the work done in [SEAR-1253](https://spothero.atlassian.net/browse/SEAR-1253) but is blocked until [SEAR-1255](https://spothero.atlassian.net/browse/SEAR-1255) is complete as tests will not successfully deserialize until then.
> Added commuter_card_eligible property to monthly

- Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift
- Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityResult.swift
Updated this to match the spec defined in [SEAR-1271](https://spothero.atlassian.net/browse/SEAR-1271).
This is a **breaking change**.
> Updated the Transient spec for commuted card eligibility

- Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate.swift
This implements the frontend work for the properties added in [SEAR-1261](https://spothero.atlassian.net/browse/SEAR-1261).
> Implemented access_hours in MonthlyRate

- Sources/SpotHeroAPI/Search/Common/Models/FacilityOptions.swift
> Made isCommuterCardEligible property public

- Package.resolved
- Package.swift
- SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Tests/SpotHeroAPITests/Core/XCTestCase+Stub.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2691
Updates to UtilityBelt for card https://spothero.atlassian.net/browse/IOS-2691 are being integrated into SpotHeroSDK so that the main SpotHero-iOS app can be updated to use UtilityBelt-iOS 0.6.0 as well.
> IOS-2691: Feature/Integrate UtilityBelt 0.6.0

- Package.resolved
- Package.swift
> Feature/Update UtilityBelt to get debug logging changes

- Package.resolved
- Package.swift
- SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2916
Title
> IOS-2916: Feature/Bump UtilityBelt

- Package.swift
- SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Update UtilityBelt to v0.10.1

- Package.resolved
- Package.swift
- Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift
- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift
- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
Updated UtilityBelt to v0.11.0, which updates to use a new `Request` object and supports `RequestInterceptor`s.
> Feature/Update UtilityBelt to v0.11.0

- Package.resolved
- Package.swift
Updated to the latest UtilityBelt version.
> Feature/Bump UtilityBelt Version

- Sources/SpotHeroAPI/Search/Airport/Models/AirportFacilityResult.swift
- Sources/SpotHeroAPI/Search/Common/Models/Availability.swift
- Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyFacilityResult.swift
- Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityResult.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3457
Updated SpotHeroSDK to begin parsing availability information when performing searches
> IOS-3457: Ensure spots are available when using the searchTransientFacilityParking endpoint

- Package.resolved
- Package.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3809
Needs to update UtilityBelt to use it internally.
> Updated Packages

- Tests/SpotHeroAPITests/Core/APITestCase.swift
**Issue Link**
N/A
Remove reference to Mobile Staging as we are moving away from it.
> Remove reference to Mobile Staging

- Mintfile
- Package.resolved
- Package.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
- SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4158
Adds a facility exclusion experiment property on transient requests.
> IOS-4158 (Part 1): Feature/Facility Exclusion Property on Transient

- Sources/SpotHeroAPI/Search/Transient/Models/TransientRate.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4354
added the group title to the transient search parsing.
> IOS-4354: added the group title to the transient search parsing.

- Sources/SpotHeroAPI/Search/Airport/Models/AirportFacilityResult.swift
- Sources/SpotHeroAPI/Search/SearchEndpoint.swift
- Sources/SpotHeroAPI/Search/Transient/Models/BulkSearchPeriod.swift
- Sources/SpotHeroAPI/Search/Transient/Models/BulkTransientFacilitiesSearchResponse.swift
- Sources/SpotHeroAPI/Search/Transient/Models/BulkTransientFacilityResult.swift
- Sources/SpotHeroAPI/Search/Transient/Models/BulkTransientFacilitySearchResponse.swift
- Sources/SpotHeroAPI/Search/Transient/Models/BulkTransientRateContainer.swift
- Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityResult.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilityRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4336
Fairly simple changes:
- Added the new models
- Added the new endpoints
The "tricky" part was splitting up the HTTP Body and the query parameters.
> IOS-4336: Added endpoints for bulk search

- .github/workflows/ci.yml
**Issue Link**
N/A
Bumped to XCode 15
> Bumped to XCode 15

- Sources/SpotHeroAPI/Search/Common/Models/ExtensionQuoteContainer.swift
- Sources/SpotHeroAPI/Search/Transient/Models/TransientRateExtensionResponse.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientExtensionRates.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4462
Product wanted these parameters to be added. They are also not optional 
https://spothero.atlassian.net/wiki/spaces/~253418099/pages/3102146728?focusedCommentId=3106930852
> IOS-4462: Added query parameters  /v2/search/extension_rates/{facility_id} request

- .github/workflows/ci.yml
Try to use a different action for selecting xcode version
> Try to use a different action for selecting xcode version

- Sources/SpotHeroAPI/Core/Endpoints/Endpoint.swift
- Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift
- Sources/SpotHeroAPI/Core/Helpers/SpotHeroAPIClient.swift
- Sources/SpotHeroAPI/Protocols/RequestDefining.swift
- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift
- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift
- Sources/SpotHeroAPI/Search/SearchEndpoint.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilityRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientExtensionRates.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
- Tests/SpotHeroAPITests/Core/APITestCase.swift
- Tests/SpotHeroAPITests/Helpers/MockInterceptor.swift
- Tests/SpotHeroAPITests/TestCases/Search/Airport/SearchGetAirportFacilitiesRequestTests.swift
- Tests/SpotHeroAPITests/TestCases/Search/Airport/SearchGetAirportFacilityRequestTests.swift
- Tests/SpotHeroAPITests/TestCases/Search/Monthly/SearchGetMonthlyFacilitiesRequestTests.swift
- Tests/SpotHeroAPITests/TestCases/Search/Monthly/SearchGetMonthlyFacilityRequestTests.swift
- Tests/SpotHeroAPITests/TestCases/Search/Transient/SearchGetTransientFacilitiesRequestTests.swift
- Tests/SpotHeroAPITests/TestCases/Search/Transient/SearchGetTransientFacilityRequestTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4530
Added bearer token to Search requests
> IOS-4530: Added bearer token to Search requests

- Sources/SpotHeroAPI/Search/Common/Models/CommonFacilityAttributes.swift
- Sources/SpotHeroAPI/Search/Common/Models/VisualFlag.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/DRAC-1446
- Added the new `sort_by` parameter to transient search
- Added the new Visual Flag response model object.
API doc https://api.spothero.com/v2/docs#tag/Search/operation/searchTransientParking
> DRAC-1446: sort_by parameter and Visual Flag

- Sources/SpotHeroAPI/Search/Common/Models/VisualFlag.swift
- Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/DRAC-1446
Refactored to use a string for type, due to tests issues with casting directly to enum. We can use the enum on the iOS app side
> DRAC-1446: made the type optional

- Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilityRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4787
Added `sort_by=relevance` to powerbooking call.
> IOS-4787: added `sort_by=relevance` to powerbooking call.
