Sources/SpotHeroAPI/Core/Extensions/KeyedDecodingContainer+DecodeDateOnly.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyReservationDates.swift
- Added `KeyedDecodingContainer.decodeDateOnly` so we can very simply add decoding for `Date` types that match the `yyyy-MM-dd` format.
=> Created date decoding convenience method

Tests/SpotHeroAPITests/Core/APITestCase.swift
- Added `ServiceURL` enum for easy configuration between `monolith` and `craig` endpoints. This will get updated as more environments are added but is primarily intended for testing at this time.
=> Updated APITestCase to include CRAIG URL

Sources/SpotHeroAPI/Search/Common/Enums/AmenityType.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift, Tests/SpotHeroAPITests/Resources/MockFiles.bundle/CRAIG/Search/get_transient_facilities.json, Tests/SpotHeroAPITests/TestCases/RequestTests/SearchGetTransientFacilitiesRequestTests.swift
**Issue Link**
IOS-2256
- Added `SearchGetTransientFacilitiesRequest` following the paradigm from previous POCs.
- Added `Parameters` struct within this request for strongly typed parameter enforcement. It adheres to the `asParameterDictionary` function for making network requests simple.
- Added `touchless` amenity which didn't exist before! Hooray.
- Added mock file for the request.
Similar to the previous PR, no real testing of the actual search response included just yet, this is only meant to test the deserialization. Testing the full responses will likely involve mirroring the `SpotHeroAPI` v1 tests in the future.
=> IOS-2256: Implemented searchTransientParking GET Request

Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift, Tests/SpotHeroAPITests/Resources/MockFiles.bundle/CRAIG/Search/get_transient_facilities_2175.json, Tests/SpotHeroAPITests/TestCases/RequestTests/SearchGetTransientFacilityRequestTests.swift
**Issue Link**
IOS-2257
- Added `SearchGetTransientFacilityRequest` following the paradigm from previous POCs.
- Added `Parameters` struct within this request for strongly typed parameter enforcement. It adheres to the `asParameterDictionary` function for making network requests simple.
- Added mock file for the request.
- Made the `request` function on `NetworkClient` internal so it could be used in testing. Will need to figure out a smoother way to contain `Route` for a request with path parameters.
Similar to the previous PR, no real testing of the actual search response included just yet, this is only meant to test the deserialization. Testing the full responses will likely involve mirroring the `SpotHeroAPI` v1 tests in the future.
=> IOS-2257: Implemented searchTransientFacilityParking GET Request

Tests/SpotHeroAPITests/TestCases/RequestTests/SearchGetMonthlyFacilitiesRequestTests.swift
Just following the new pattern I used for other tests since this one was completed.
=> Fixed how the parameters are referenced in the monthly facilities test

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift, Tests/SpotHeroAPITests/TestCases/RequestTests/SearchGetAirportFacilitiesRequestTests.swift
**Issue Link**
IOS-2258
- Added `SearchGetAirportFacilitiesRequest` following the paradigm from previous POCs.
- Added `Parameters` struct within this request for strongly typed parameter enforcement. It adheres to the `asParameterDictionary` function for making network requests simple.
No mock files or tests yet because Airport is not fully implemented. This is just preparation.
=> IOS-2258: Implemented searchAirportParking GET Request

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift, Tests/SpotHeroAPITests/TestCases/RequestTests/SearchGetAirportFacilityRequestTests.swift
**Issue Link**
IOS-2259
- Added `SearchGetAirportFacilityRequest` following the paradigm from previous POCs.
- Added `Parameters` struct within this request for strongly typed parameter enforcement. It adheres to the `asParameterDictionary` function for making network requests simple.
No mock files or tests yet because Airport is not fully implemented. This is just preparation.
=> IOS-2259: Implemented searchAirportFacilityParking GET Request

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
**Issue Link**
IOS-2334
- Added the `origin_lat` and `origin_lon` parameters to the `GetTransientFacilitiesRequest` struct.
- Adjusted order of `CodingKeys` for various requests.
=> IOS-2334: Added origin_lat and origin_lon support

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift, Sources/SpotHeroAPI/Search/Common/Models/FacilityRating.swift, Sources/SpotHeroAPI/Search/Common/Protocols/SearchTracking.swift, Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
- `analytics_id` change never went through, so I reverted this back to `fingerprint`.
- Added a public initializer to the `SearchTrackingParameters` struct.
=> Reverted analytics_id to fingerprint

Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes+Cancellation.swift, Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift
**Issue Link**
IOS-2612
Added new `cancellation` object to `TransientFacilityAttributes`, based on the contract documented [here](https://spothero.atlassian.net/wiki/spaces/SEAR/pages/1637712304/Search+Transient+V2+Cancellation+Allowed+API+Contract)
=> IOS-2612: Added cancellation information to Transient facility

Sources/SpotHeroAPI/Search/Common/Models/Amenity.swift
**Issue Link**
IOS-2615
Added the `display_name` property to `Amenity` per [this PR](https://github.com/spothero/craig/pull/326/files).
=> IOS-2615: Added Amenity.displayName

Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
**Issue Link**
IOS-2613
- Added `is_commuter_card_eligible` property to `TransientFacilityAttributes`.
- Added the `work_lat` and `work_lon` request parameters to `SearchGetTransientFacilitiesRequest.Parameters`.
Both items are based on the contract documented [here](https://spothero.atlassian.net/wiki/spaces/SEAR/pages/1636794577/Search+Transient+V2+Commuter+Card+Benefits+API+Contract+-+Short+Term)
=> IOS-2613: Added is_commuter_card_eligible property to Transient facility

Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes+EarlyBird.swift, Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift
**Issue Link**
IOS-2614
Added the `early_bird` property to `facility.transient` per the documentation [here](https://spothero.atlassian.net/wiki/spaces/SEAR/pages/1640071211/Search+Transient+V2+Early+Bird+Rate+Fields+API+Contract).
=> IOS-2614: Added Early Bird information to the Transient facility

Sources/SpotHeroAPI/Search/Common/Models/CommonFacilityAttributes.swift, Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityAttributes.swift
`cancellation` is moving from `facility.transient` to `facility.common` since it applies across all verticals.
=> Moving cancellation to match change in spec

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift
Updating this due to a change the occurred six months ago: https://github.com/spothero/craig/pull/278
Please let me know if you prefer the parameter to be `iataCode` or `airportCode`. I think I lean towards the latter, but I implemented it as the former to match the spec closer.
=> Updated airport parameter to iata

Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift
Copied over the `originLatitude` and `originLongitude` properties from the Transient version of this request, now that Search V2 Monthly has these properties.
=> Added origin_lat and origin_lon to monthly search request

Sources/SpotHeroAPI/Search/Airport/Models/AirportFacilityAttributes.swift, Sources/SpotHeroAPI/Search/Common/Models/CommonFacilityAttributes.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate+ParkingPass.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyReservationDates.swift, Tests/SpotHeroAPITests/Core/APITestCase.swift, Tests/SpotHeroAPITests/TestCases/Search/Airport/SearchGetAirportFacilitiesRequestTests.swift, Tests/SpotHeroAPITests/TestCases/Search/Airport/SearchGetAirportFacilityRequestTests.swift, Tests/SpotHeroAPITests/TestCases/Search/Monthly/SearchGetMonthlyFacilitiesRequestTests.swift, Tests/SpotHeroAPITests/TestCases/Search/Monthly/SearchGetMonthlyFacilityRequestTests.swift, Tests/SpotHeroAPITests/TestCases/Search/Transient/SearchGetTransientFacilitiesRequestTests.swift, Tests/SpotHeroAPITests/TestCases/Search/Transient/SearchGetTransientFacilityRequestTests.swift
- Added a ton of new fields to the `MonthlyRate` related to the work done in [SEAR-1241](https://spothero.atlassian.net/browse/SEAR-1241).
- Modified the `airport.logo` to be nullable as the docs state.
- Skipping all mock tests again--this is such a pain to maintain while the API is constantly being revised. Once active development is complete, I'll re-enable and update.
Notably, `parking_pass.type` is an enum, but for now I'm marking it as a `String` while I look at how it gets used to see what our best course of action is regarding not having this break our application if new values are added.
=> Implemented new changes to MonthlyRate, skipped mock tests

Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift
Implemented the `work_lat` and `work_lon` parameters for Monthly search requests.
Corresponds to the work associated with [SEAR-1253](https://spothero.atlassian.net/browse/SEAR-1253) and [SEAR-1275](https://spothero.atlassian.net/browse/SEAR-1275).
=> Added work_lat and work_lon to monthly search request

Sources/SpotHeroAPI/Search/Common/Models/HoursOfOperationPeriod.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate+ParkingPass.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyRate.swift
Just looking to make this more flexible instead of restrictive. We don't use these values as enum types on our end at all, and doing this will allow the display format to be flexible and for `hours_type` to eventually included new types without impact on this SDK.
=> Converted HoursOfOperationPeriod properties to raw strings from enums

Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
**Issue Link**
IOS-3027
Simple change here, but essentially our API logic changed a short while ago, so our docs should obviously be updated as well.
=> IOS-3027: Updated the doc comment for maxDistanceMeters

Sources/SpotHeroAPI/Search/Common/Models/CommonFacilityAttributes.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2473
Adds a property onto `CommonFacilityAttributes` that will be used to determine if a facility allows reservations to be extended after purchase.
=> IOS-2473: Feature/Add `reservationExtensionEnabled` property to `CommonFacilityAttributes`

.github/workflows/ci.yml
Updating our GitHub Actions YAML to use Xcode 13 and iOS/tvOS 15. 
- I removed the `DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer` line as I was getting errors about that directory not existing
- Changed ` macos-latest` to `macos-11` as "latest" was not using Big Sur
- Added a line in each workflow to manually switch to the new version of Xcode using `xcode-select` (When searching for how to set the Xcode version in Github Actions YAML, not much documentation exists and I can't find anything on the `DEVELOPER_DIR` environment variable, but I've seen other repos using the `xcode-select` method and it seems a bit more straightforward
=> Update to Xcode 13, iOS 15, tvOS 15

Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift, Sources/SpotHeroAPI/Core/Helpers/SpotHeroAPIClient.swift, SpotHeroSDK.xcworkspace/xcshareddata/swiftpm/Package.resolved
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3415
- Allow for an `HTTPClient` to be injected when setting up networking clients, which will enable capabilities such as mocking network requests 
- Updated UtilityBelt
=> IOS-3415: Feature/Allow HTTPClient injection

Sources/SpotHeroAPI/Search/Common/Enums/FacilityFee.swift, Sources/SpotHeroAPI/Search/Common/Models/CommonFacilityAttributes.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3482
- Adds the new `event_fee` type to `FacilityFee`
- Updates `CommonFacilityAttributes` to use an array of strings rather than an array of finite enum values. This avoids potentially parsing issues if the API introduces new fee types in the future.
=> IOS-3482: Feature/Add event fee support

Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3513
The expected value is a double for `max_distance_meters`. Updates from Int to a Double.
=> IOS-3513: Bugfix/Use a double value for the max distance

Sources/SpotHeroAPI/Search/Airport/Models/AirportFacility.swift, Sources/SpotHeroAPI/Search/Common/Protocols/CommonFacility.swift, Sources/SpotHeroAPI/Search/Monthly/Models/MonthlyFacility.swift, Sources/SpotHeroAPI/Search/Transient/Models/TransientFacility.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3538
Creates a common facility protocol that can be used to reference facilities generally in SpotHero-iOS.
This is needed for the updates in https://github.com/spothero/SpotHero-iOS/pull/5874
=> IOS-3538: (Part 5) Feature/Creates a common facility protocol

Sources/SpotHeroAPI/Core/Helpers/NetworkClient.swift, Sources/SpotHeroAPI/Core/Helpers/SpotHeroAPIClient.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3533?atlOrigin=eyJpIjoiZGI3NzNkYTgyYjAzNGU4MTllOWM4MTM4MGFhNmE3MDIiLCJwIjoiaiJ9
The issue is that when making a network request we do not assign `User-Agent` property to a request's header. This causes issue like the one reported in the ticket where we display unavailable spots that were turned off to mobile by BE
=> IOS-3533: Updated user agent in network' request header

Sources/SpotHeroAPI/Search/Monthly/Requests/SearchGetMonthlyFacilityRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3897
Follow up on #97: we need to pass in the `originLatitude` and `originLongitude` to get the distance information.
=> IOS-3897: Added originLatitude and originLongitude for distance calculations

.github/workflows/ci.yml
https://spothero.atlassian.net/browse/SEAR-2372
Adds repository_dispatch event to be able to trigger testing remotely.
This has proven working in the canary, see https://github.com/spothero/canary/blob/main/.github/workflows/manual.yml
Context: https://spothero.slack.com/archives/CBB351AV9/p1674494343004789
=> SEAR-2372 add github action hook repository_dispatch to trigger testing

.github/workflows/ci.yml, Package.swift
**Issue Link**
N/A
Update GitHub Actions to a more modern OS and Xcode version.
Updates SPM version.
Addresses an outdated GitHub Action that was causing warnings, checkout updated to v3.5.0.
This came about from a discussion that there were failing actions occurring. https://spothero.slack.com/archives/C010V0UQRC4/p1680721297556799
=> Update GitHub Actions

Sources/SpotHeroAPI/Search/Common/Models/Availability.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4087
- Adds `available_spaces` in `Availability` when the API sends it for us to consume.
=> IOS-4087: Added available spaces

Tests/SpotHeroAPITests/TestCases/Search/Airport/SearchGetAirportFacilityRequestTests.swift
**Issue Link**
N/A
The ID we were using didn't exist anymore
=> Fixed tests

Sources/SpotHeroAPI/Search/Transient/Models/TransientRate.swift
**Issue Link**
N/A
Misunderstanding with BE team. Turned out rate_type should be an optional
=> Make rate_type optional

Sources/SpotHeroAPI/Search/Transient/Models/TransientRate.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4640
This is currently only available on sandbox so I overrode the synthesized `init(from:)` to default to 0 -- I didn't want to make it optional because when it is deployed to production, it won't be.
=> IOS-4640: Added cancellationThresholdInMinutes

Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilitiesRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4787
Part 1 https://github.com/spothero/SpotHeroSDK-iOS/pull/120
Turns out we need both `BulkSearchGetTransientFacilityRequest` and `BulkSearchGetTransientFacilitiesRequest` to have sort by relevance code.
=> IOS-4787: Part 2 - BulkSearchGetTransientFacilitiesRequest sort by relevance.

Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Airport/Requests/SearchGetAirportFacilityRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/BulkSearchGetTransientFacilityRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientExtensionRates.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilitiesRequest.swift, Sources/SpotHeroAPI/Search/Transient/Requests/SearchGetTransientFacilityRequest.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4758
included the `vehicle_info_id` in search everywhere we had `oversize` except for monthly.
=> iOS-4758: `vehicle_info_id` in search

Sources/SpotHeroAPI/Search/Common/Models/OversizeVehicleFeeInformation.swift, Sources/SpotHeroAPI/Search/Transient/Models/BulkTransientFacilityResult.swift, Sources/SpotHeroAPI/Search/Transient/Models/TransientFacilityResult.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-4814
Added new fields required for the oversize project.
A new object has been added at the root level:
- `vehicle` (nullable)
- `onsite_fee` (nullable): contains information about the fee that the customer will have to pay on site if their vehicle is considered oversize.
- `currency_code`: the currency code.
- `value`: the price to pay on site in pennies.
- `oversize_type`: The type of oversize fee. We can ignore this for now (it was added to future proof the API). Right now the only value will be oversize.
- `oversize_policy_id`: Can be safely ignored. This is for internal audit only.
- `unknown_onsite_fee`: A boolean value indicating whether the onsite_fee is unknown or not.
=> IOS-4814: Added vehicle information for oversize fees
